### ISSUE TITLE
location stream doesn't broadcast non-managed locations on deeplinking

### ISSUE THREAD

**Issue by cristiano-belloni** [zambezi/caballo-vivo#14]
...but it does when we click on `Link`s (seemingly because they come from `history`)

**Comment by cristiano-belloni** [comment]
@gabrielmontagne was this fixed? I can;t remember

**Comment by gabrielmontagne** [comment]
I think not.   I think that fix stayed on our "enterprise fork"---would be good to bring that in, though.

**Comment by cristiano-belloni** [comment]
No @gabrielmontagne , @gabrielmontagne is informing me that it's actually fixed.
