### ISSUE TITLE
Port to RxJS 6

### ISSUE THREAD

**Issue by cristiano-belloni** [zambezi/caballo-vivo#2]
https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md - One step towards rxjs 6

**Comment by gabrielmontagne** [comment]
As discussed today offline, let's go all the way through to RxJS 6 -- no need to linger on the migration pains.

**Comment by cristiano-belloni** [comment]
Renamed!

**Comment by cristiano-belloni** [comment]
https://github.com/zambezi/caballo-vivo/pull/11
